=== ulfloodcenter/carma-schema/src/schema/CARMA-schema-20200709.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://floodcenter.louisiana.edu/CARMA.schema.20200709.json",
  "title": "CARMA schema",
  "description": "Data schema for Coastal Aquifer Research and Management Analytics (CARMA) Platform",
  "type": "object",
  "required": ["HUC12Watersheds"],
  "properties": {
  	"HUC12Watersheds": {
  		"type": "array",
  		"items": { "$ref": "#/definitions/HUC12Watershed" },
  		"minItems": 1,
      	"uniqueItems": true
  	},
  	"GroundWaterAvailabilityDatasets": {
  		"type": "array",
  		"items": { "$ref": "#/definitions/GroundWaterAvailabilityDataset" },
  		"minItems": 1,
  		"uniqueItems": true
  	},
  	"SurfaceWaterAvailabilityDatasets": {
		"type": "array",
		"items": { "$ref": "#/definitions/SurfaceWaterAvailabilityDataset" },
		"minItems": 1,
		"uniqueItems": true
  	},
  	"WaterUseDatasets": {
  		"type": "array",
		"items": { "$ref": "#/definitions/WaterUseDataset" },
		"minItems": 1,
		"uniqueItems": true
  	}
  },
  "definitions": {
  	"HUC12Watershed": {
  		"type": "object",
  		"required": ["id", "description", "geometry", "area", "cropArea", "developedArea", "maxStreamOrder", "environmentalFlow"],
  		"properties": {
  			"id": {
  				"type": "string",
  				"description": "The ID of the HUC-12, e.g.: 111402010000"
  			},
  			"description": {
  				"type": "string",
  				"description": "A description for the HUC-12 watershed"
  			},
  			"geometry": {
  				"$ref": "https://geojson.org/schema/Feature.json"
  			},
  			"area": {
  				"type": "number",
  				"description": "The total area of the HUC-12 watershed (unit: ha)"
  			},
  			"cropArea": {
  				"type": "number",
  				"description": "The crop area of the HUC-12 watershed (unit: ha)"
  			},
  			"developedArea": {
  				"type": "number",
  				"description": "The developer area of the HUC-12 watershed (unit: ha)"
  			},
  			"maxStreamOrder": {
  				"type": "number",
  				"description": "The maximum Strahler order of streams in the HUC-12 (unitless)"
  			},
  			"environmentalFlow": {
  				"type": "number",
  				"description": "Streamflow required for maintaining habitat suitability (unit: mm)"
  			}
  		}
  	},
  	"GroundWaterAvailabilityDataset": {
  		"type": "object",
  		"required": ["huc12", "description", "sourceData", "year", "value", "unit"],
  		"properties": {
  			"huc12": {
  				"type": "string",
  				"description": "The ID of the HUC-12 watershed that this dataset is associated with"
  			},
  			"description": {
  				"type": "string",
  				"description": "A description of the ground water dataset"
  			},
  			"sourceData": {
  				"type": "string",
  				"description": "A URI referring to the original source of the dataset"
  			},
  			"year": {
  				"type": "number",
  				"description": "The year that the value of the dataset represents"
  			},
  			"value": {
  				"type": "number",
  				"description": "The datum that the dataset represents"
  			},
  			"unit": {
  				"$ref": "#/definitions/Unit"
  			}
  		}
  	},
  	"SurfaceWaterAvailabilityDataset": {
  		"type": "object",
  		"required": ["huc12", "description", "sourceData", "year", "value", "unit"],
  		"properties": {
  			"huc12": {
  				"type": "string",
  				"description": "The ID of the HUC-12 watershed that this dataset is associated with"
  			},
  			"description": {
  				"type": "string",
  				"description": "A description of the ground water dataset"
  			},
  			"sourceData": {
  				"type": "string",
  				"description": "A URI referring to the original source of the dataset"
  			},
  			"year": {
  				"type": "number",
  				"description": "The year that the value of the dataset represents"
  			},
  			"value": {
  				"type": "number",
  				"description": "The datum that the dataset represents"
  			},
  			"unit": {
				"$ref": "#/definitions/Unit"
			}
  		}
  	},
  	"WaterUseDataset": {
  		"type": "object",
  		"required": ["huc12", "useType", "sector", "description", "sourceData", "year", "value", "unit"],
  		"properties": {
  			"huc12": {
  				"type": "string",
  				"description": "The ID of the HUC-12 watershed that this dataset is associated with"
  			},
  			"useType": {
				"$ref": "#/definitions/UseType"	  
			},
  			"sector": {
				"$ref": "#/definitions/Sector"	  
			},
			"description": {
				"type": "string",
				"description": "A description of the water use dataset"
			},
  			"sourceData": {
  				"type": "string",
  				"description": "A URI referring to the original source of the dataset"
  			},
  			"year": {
  				"type": "number",
  				"description": "The year that the value of the dataset represents"
  			},
  			"value": {
  				"type": "number",
  				"description": "The datum that the dataset represents"
  			},
  			"unit": {
				"$ref": "#/definitions/Unit"
			}
  		}
  	},
  	"Unit": {
  		"type": "object",
  		"required": ["name"],
  		"properties": {
  			"name": {
  				"type": "string",
  				"description": "The abbreviation of the unit."
  			},
  			"description": {
  				"type": "string",
  				"description": "A more detailed description of the unit."
  			},
  			"primaryDimension": {
				"$ref": "#/definitions/Dimension"
  			},
  			"secondaryDimension": {
				"$ref": "#/definitions/Dimension"
  			},
  			"tertiaryDimension": {
				"$ref": "#/definitions/Dimension"
  			}
  		}
  	},
  	"Dimension": {
  		"type": "object",
  		"required": ["name"],
  		"properties": {
  			"name": {
  				"type": "string",
  				"enum": ["Millimeter", "Meter", "Cubic meter", "Hectare", "Liter", "Million liter", "Kilogram", "Kelvin", "Second", "Minute", "Hour", "Day", "Year"]
  			}
  		}
  	},
  	"UseType": {
  		"type": "object",
  		"required": ["name"],
  		"properties": {
  			"name": {
  				"type": "string",
  				"enum": ["Surface Water", "Ground Water"]
  			}
  		}
  	},
  	"Sector": {
  		"type": "object",
  		"required": ["name"],
  		"properties": {
  			"name": {
  				"type": "string",
  				"enum": ["Public Supply", "Domestic", "Commercial", "Industrial", "Total Thermoelectric Power", "Fossil-fuel Thermoelectric Power", "Geothermal Thermoelectric Power", "Nuclear Thermoelectric Power", "Thermoelectric Power (Once-through cooling)", "Thermoelectric Power (Closed-loop cooling)", "Mining", "Livestock", "Livestock (Stock)", "Livestock (Animal Specialities)", "Aquaculture", "Irrigation, Total", "Irrigation, Crop", "Irrigation, Golf Courses", "Hydroelectric Power", "Wastewater Treatment"]
  			}
  		}
  	}
  }
}

=== ulfloodcenter/carma-schema/tests/fixtures/sample_carma_data_1.json
{
	"GroundWaterAvailabilityDatasets": [
		{
			"huc12": "080801030109",
			"year": 2002,
			"description": "This data set represents the mean annual natural groundwater recharge, in millimeters, compiled for every catchment of NHDPlus for the conterminous United States. The source data set is Estimated Mean Annual Natural Ground-Water Recharge in the Conterminous United States (Wolock, 2003).",
			"sourceData": "https://water.usgs.gov/GIS/metadata/usgswrd/XML/nhd_recharge.xml",
			"value": 123.45,
			"unit": {
				"name": "mm/yr",
				"primaryDimension": { "name": "Millimeter" },
				"secondaryDimension": { "name": "Year" }
			}
		},
		{
			"huc12": "080801030305",
			"year": 2002,
			"description": "This data set represents the mean annual natural groundwater recharge, in millimeters, compiled for every catchment of NHDPlus for the conterminous United States. The source data set is Estimated Mean Annual Natural Ground-Water Recharge in the Conterminous United States (Wolock, 2003).",
			"sourceData": "https://water.usgs.gov/GIS/metadata/usgswrd/XML/nhd_recharge.xml",
			"value": 54.321,
			"unit": {
				"name": "mm/yr",
				"primaryDimension": { "name": "Millimeter" },
				"secondaryDimension": { "name": "Year" }
			}
		}
	],

	"SurfaceWaterAvailabilityDatasets": [
		{
			"huc12":"080801030109",
			"description": "NHDPlus V21 National Seamless Geodatabase, December 4, 2016",
			"sourceData": "https://www.epa.gov/waterdata/nhdplus-national-data",
			"year": 2016,
			"value": 2069.587,
			"unit": {
				"name": "cubic meter/sec",
				"primaryDimension": { "name": "Cubic meter" },
				"secondaryDimension": { "name": "Second" }
			}
		},
		{
			"huc12":"080801030305",
			"description": "NHDPlus V21 National Seamless Geodatabase, December 4, 2016",
			"sourceData": "https://www.epa.gov/waterdata/nhdplus-national-data",
			"year": 2016,
			"value": 3029.587,
			"unit": {
				"name": "cubic meter/sec",
				"primaryDimension": { "name": "Cubic meter" },
				"secondaryDimension": { "name": "Second" }
			}
		}
	],

	"WaterUseDatasets": [
		{
			"huc12":"080801030109",
			"useType": { "name": "Ground Water" },
			"sector": { "name": "Public Supply" },
			"description": "Water use by public water utilities",
			"sourceData": "https://waterdata.usgs.gov/la/nwis/water_use?format=rdb&rdb_compression=file&wu_area=County&wu_year=2015&wu_county=001&wu_category=PS&wu_county_nms=Acadia%2BParish&wu_category_nms=Public%2BSupply",
			"year": 2015,
			"value": 20.6,
			"unit" : {
				"name": "million liter/day",
				"primaryDimension": { "name": "Million liter" },
				"secondaryDimension": { "name": "Day" }
			}
		},
		{
			"huc12":"080801030305",
			"useType": { "name": "Ground Water" },
			"sector": { "name": "Public Supply" },
			"description": "Water use by public water utilities",
			"sourceData": "https://waterdata.usgs.gov/la/nwis/water_use?format=rdb&rdb_compression=file&wu_area=County&wu_year=2015&wu_county=001&wu_category=PS&wu_county_nms=Acadia%2BParish&wu_category_nms=Public%2BSupply",
			"year": 2015,
			"value": 42.8,
			"unit" : {
				"name": "million liter/day",
				"primaryDimension": { "name": "Million liter" },
				"secondaryDimension": { "name": "Day" }
			}
		}
	],
	
	"HUC12Watersheds": [
		{
		"id": "080801030109",
		"description": "Anselm Coulee-Vermilion River",
		"area": 14270.417803582170405,
		"cropArea": 4270.217040541780358,
		"developedArea": 270.435821780170405,
		"maxStreamOrder": 5,
		"environmentalFlow": 105,
		"geometry":
			{ "type": "Feature", "properties": { "OBJECTID_1": 73029, "OBJECTID": 232771, "HUC_8": "08080103", "HUC_10": "0808010301", "HUC_12": "080801030109", "ACRES": 35262.9703505, "NCONTRB_A": 0.0, "HU_10_GNIS": null, "HU_12_GNIS": null, "HU_10_DS": "0808010302", "HU_10_NAME": "Upper Vermilion River", "HU_10_MOD": "GC,TF", "HU_10_TYPE": "S", "HU_12_DS": "080801030202", "HU_12_NAME": "Anselm Coulee-Vermilion River", "HU_12_MOD": "PS,ID,DD,LE,UA", "HU_12_TYPE": "S", "META_ID": "LA02", "STATES": "LA", "GlobalID": "{FEA2F0FE-AB5C-42CD-B000-A3DF8B6F2A45}", "SHAPE_Leng": 0.81124135481000004, "GAZ_ID": -387406, "WBD_Date": "2012\/02\/01", "VPUID": "08", "Shape_Area": 0.01336164587, "AreaHUC12": 142.704178036 }, "bbox": [ -92.110145209999928, 30.058345103000079, -91.956448063999915, 30.235076509000066 ], "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -92.009638043999928, 30.213069800000085 ], [ -92.009230019999904, 30.213200440000037 ], [ -92.008946205999905, 30.213353752000049 ], [ -92.008455783999921, 30.213790505000077 ], [ -92.007836152999914, 30.214477687000056 ], [ -92.007560246999901, 30.214809207000091 ], [ -92.007386019999899, 30.214940355000067 ], [ -92.007128619999946, 30.215089944000052 ], [ -92.006612977999907, 30.215290469000081 ], [ -92.006424194999909, 30.215400328000047 ], [ -92.006029077999926, 30.215630149000049 ], [ -92.005841937999946, 30.215796420000061 ], [ -92.005427038999926, 30.216401796000071 ], [ -92.00498968799991, 30.21724994200008 ], [ -92.004718583999932, 30.217724051000058 ], [ -92.004427740999915, 30.218116655000074 ], [ -92.004262298999947, 30.218266276000065 ], [ -92.004170278999936, 30.218330403000039 ], [ -92.003230406999933, 30.218828476000059 ], [ -92.00297301899991, 30.218899259000068 ], [ -92.001696391999928, 30.218741513000055 ], [ -92.000810336999905, 30.218734761000064 ], [ -92.000538714999948, 30.218790572000046 ], [ -92.000256771999943, 30.218919889000063 ], [ -91.999975951999943, 30.219207372000085 ], [ -91.998834968999915, 30.219902062000077 ], [ -91.998811722999903, 30.219911383000067 ], [ -91.998497192999935, 30.219980092000071 ], [ -91.997392870999931, 30.219886271000064 ], [ -91.99722218799991, 30.219934306000088 ], [ -91.996840851999934, 30.220194477000064 ], [ -91.996056195999927, 30.220603648000068 ], [ -91.995716134999896, 30.220738388000086 ], [ -91.99456429199995, 30.220985621000068 ], [ -91.993674861999921, 30.22105360300009 ], [ -91.993175115999918, 30.221091754000046 ], [ -91.992690809999942, 30.221189377000087 ], [ -91.991956381999898, 30.221466110000055 ], [ -91.991454223999938, 30.221757046000047 ], [ -91.990917107999906, 30.221949322000057 ], [ -91.990657296999927, 30.221984837000036 ], [ -91.990215644999921, 30.221985241000084 ], [ -91.989500953999936, 30.221899527000062 ], [ -91.988705646999904, 30.221760371000073 ], [ -91.988035779999905, 30.22164923400004 ], [ -91.987741521999908, 30.221653209000067 ], [ -91.987367971999902, 30.221719477000082 ], [ -91.986816252999915, 30.221932135000092 ], [ -91.986566367999899, 30.221983315000042 ], [ -91.985792765999918, 30.221977332000051 ], [ -91.984778223999925, 30.22186447100006 ], [ -91.984373275999928, 30.221854753000059 ], [ -91.983341278999944, 30.222011562000034 ], [ -91.982605748999902, 30.222032464000051 ], [ -91.981872193999948, 30.222026768000035 ], [ -91.981470419999951, 30.221969425000058 ], [ -91.980435749999913, 30.221510054000074 ], [ -91.97987874699993, 30.221099559000038 ], [ -91.979619976999913, 30.220964042000048 ], [ -91.9790258699999, 30.220907783000087 ], [ -91.978758350999897, 30.220927024000051 ], [ -91.978653233999921, 30.220967749000067 ], [ -91.977729997999916, 30.221534144000092 ], [ -91.976969689999919, 30.222098920000064 ], [ -91.976131303999921, 30.222911421000049 ], [ -91.975827418999927, 30.223297649000077 ], [ -91.975412005999942, 30.224371103000067 ], [ -91.975274289999902, 30.224928203000047 ], [ -91.975099504999946, 30.225279589000081 ], [ -91.97508483699994, 30.22529858300004 ], [ -91.974821284999905, 30.225578531000053 ], [ -91.973166473999925, 30.226427091000062 ], [ -91.972796615999926, 30.226537031000078 ], [ -91.972523501999945, 30.226560763000069 ], [ -91.970241690999899, 30.226565619000045 ], [ -91.969138972999929, 30.226530341000057 ], [ -91.967092883999896, 30.226774504000048 ], [ -91.966749230999952, 30.226880755000082 ], [ -91.966297017999921, 30.227135838000038 ], [ -91.965895897999928, 30.22738116000005 ], [ -91.965606434999927, 30.227514741000054 ], [ -91.965335596999935, 30.227678557000047 ], [ -91.964817742999927, 30.227881261000054 ], [ -91.964513535999913, 30.227890351000042 ], [ -91.964236198999913, 30.227853678000088 ], [ -91.964078981999933, 30.227714644000056 ], [ -91.963919786999909, 30.227561330000068 ], [ -91.9637743319999, 30.227364253000079 ], [ -91.963659618999941, 30.227251244000062 ], [ -91.963447453999947, 30.227185588000058 ], [ -91.963284211999905, 30.227186957000072 ], [ -91.963131836999935, 30.227247919000035 ], [ -91.962996751999924, 30.227510860000052 ], [ -91.962921630999915, 30.227749807000066 ], [ -91.962729899999943, 30.228060753000076 ], [ -91.962536452999942, 30.228149775000077 ], [ -91.961864825999896, 30.22824158800006 ], [ -91.961627580999902, 30.228213207000071 ], [ -91.961192718999939, 30.22808350400004 ], [ -91.960953805999907, 30.227978788000083 ], [ -91.960473731999926, 30.227635718000045 ], [ -91.96023365799995, 30.227395085000069 ], [ -91.960202275999919, 30.227343793000045 ], [ -91.960018275999929, 30.226773660000049 ], [ -91.960008528999936, 30.226450253000053 ], [ -91.960165411999924, 30.225503681000077 ], [ -91.96016134599995, 30.225097417000086 ], [ -91.960046438999939, 30.224882135000087 ], [ -91.959146071999896, 30.224019424000062 ], [ -91.957596803999934, 30.222756551000092 ], [ -91.956738958999949, 30.221889247000036 ], [ -91.95661569799995, 30.221676261000084 ], [ -91.956566376999945, 30.221486113000083 ], [ -91.956611052999904, 30.221197031000088 ], [ -91.95677195199994, 30.220928685000047 ], [ -91.956979811999929, 30.220751488000076 ], [ -91.957219507999923, 30.220666648000076 ], [ -91.957630968999922, 30.220638874000084 ], [ -91.957970369999941, 30.220688365000054 ], [ -91.958269559999906, 30.220777638000076 ], [ -91.958581190999951, 30.220958523000036 ], [ -91.958983002999901, 30.221289407000086 ], [ -91.959622547999913, 30.221710143000049 ], [ -91.961671937999938, 30.222735678000046 ], [ -91.962393315999918, 30.222936358000084 ], [ -91.962579897999944, 30.22294504300
